In [1]:
import numpy as np

In [9]:
a = np.arange(0, 10)

In [10]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
type(a)

numpy.ndarray

In [12]:
a.dtype

dtype('int64')

In [24]:
a.ndim

1

In [27]:
a.shape

(10,)

In [26]:
a.size

10

In [29]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
type(a2)

numpy.ndarray

In [31]:
a2.ndim

2

In [32]:
a2.shape

(2, 4)

In [33]:
a2.size

8

In [34]:
a2.dtype

dtype('int64')

In [36]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
z = np.ones((5,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
i = np.identity(6)
i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [51]:
a = np.linspace(0, 10, 21)
a

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [57]:
a = np.arange(0, 10.5, 0.5)
a

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [58]:
a

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

### Vectorized operations

In [62]:
a % 10

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5, 0. ])

In [63]:
%timeit np.arange(1,10000) * 2.0

12.9 µs ± 331 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [64]:
%timeit [x*2.0 for x in range(10000)]

559 µs ± 7.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [67]:
p1 = np.array([1,2,3,4,5])
p2 = np.array([6,5,4,3,2])
p1 + p2

array([7, 7, 7, 7, 7])

In [68]:
min(a)

0.0

In [69]:
max(a)

10.0

In [70]:
sum(a)

105.0

In [71]:
np.min(a)

0.0

In [72]:
np.max(a)

10.0

In [74]:
np.sum(a)

105.0

In [77]:
%timeit sum(np.arange(100000))

7.04 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [78]:
%timeit np.sum(np.arange(100000))

76.4 µs ± 730 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [80]:
a ** 2

array([  0.  ,   0.25,   1.  ,   2.25,   4.  ,   6.25,   9.  ,  12.25,
        16.  ,  20.25,  25.  ,  30.25,  36.  ,  42.25,  49.  ,  56.25,
        64.  ,  72.25,  81.  ,  90.25, 100.  ])

In [81]:
np.power(a, 2)

array([  0.  ,   0.25,   1.  ,   2.25,   4.  ,   6.25,   9.  ,  12.25,
        16.  ,  20.25,  25.  ,  30.25,  36.  ,  42.25,  49.  ,  56.25,
        64.  ,  72.25,  81.  ,  90.25, 100.  ])

In [82]:
large = np.arange(10000)

%timeit large ** 2

3.17 µs ± 54.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [83]:
%timeit np.power(large, 2)

19.9 µs ± 512 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Shape

In [85]:
a = np.arange(27)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [87]:
b = a.reshape((3,9))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [88]:
a.shape

(27,)

In [89]:
b.shape

(3, 9)

In [90]:
c = a.reshape((3,3,3))
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [94]:
a

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26])

In [93]:
a[0] = 9999

In [95]:
b

array([[9999,    1,    2,    3,    4,    5,    6,    7,    8],
       [   9,   10,   11,   12,   13,   14,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23,   24,   25,   26]])

In [96]:
c

array([[[9999,    1,    2],
        [   3,    4,    5],
        [   6,    7,    8]],

       [[   9,   10,   11],
        [  12,   13,   14],
        [  15,   16,   17]],

       [[  18,   19,   20],
        [  21,   22,   23],
        [  24,   25,   26]]])

In [98]:
d = c.copy()
d

array([[[9999,    1,    2],
        [   3,    4,    5],
        [   6,    7,    8]],

       [[   9,   10,   11],
        [  12,   13,   14],
        [  15,   16,   17]],

       [[  18,   19,   20],
        [  21,   22,   23],
        [  24,   25,   26]]])

In [99]:
a[0] = 0

In [100]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [101]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [102]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
d

array([[[9999,    1,    2],
        [   3,    4,    5],
        [   6,    7,    8]],

       [[   9,   10,   11],
        [  12,   13,   14],
        [  15,   16,   17]],

       [[  18,   19,   20],
        [  21,   22,   23],
        [  24,   25,   26]]])

### Random

In [106]:
r = np.random.randint(10, 20, 20).reshape((4,5))
r

array([[14, 17, 16, 19, 15],
       [11, 16, 11, 14, 15],
       [10, 18, 11, 14, 11],
       [17, 12, 15, 16, 18]])

In [109]:
np.random.random(20)

array([0.18598799, 0.21325086, 0.72844433, 0.04684254, 0.83324783,
       0.11373489, 0.83744143, 0.11264675, 0.63083761, 0.23843291,
       0.53338566, 0.22702435, 0.78405717, 0.76595161, 0.84168842,
       0.09436509, 0.86702367, 0.72373178, 0.24888194, 0.58575327])

In [112]:
3 * np.random.randn(20) + 10

array([11.01150764, 11.48208897, 13.82520814,  6.54799629,  6.58768355,
       10.48513727,  7.96911386,  9.2749363 ,  9.49647906,  7.98016913,
       10.50527697, 10.98561818,  4.04634285, 11.23345564,  5.10108488,
        2.83993935, 13.54281162,  9.84064845, 17.82097221, 13.1480475 ])

In [115]:
np.random.normal(loc=10, scale=3, size=20)

array([14.37959096, 10.6254462 , 11.57267749,  8.88409224,  3.96247651,
        9.88180434, 13.76874876, 11.45745512,  8.96956529,  4.8571847 ,
       11.7133927 ,  6.57594037, 11.90685447, 13.37046628,  8.85894504,
       11.87172942, 12.7215542 ,  7.89941666,  9.83144627,  7.1737408 ])

In [116]:
np.random.choice(['A','B','C'], 20)

array(['C', 'A', 'B', 'A', 'C', 'A', 'A', 'A', 'B', 'A', 'B', 'C', 'C',
       'C', 'A', 'B', 'B', 'C', 'C', 'C'], dtype='<U1')