In [ ]:
import numpy as np
np.random.seed(444)

In [4]:
x = np.arange(27)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [9]:
x[0]

0

In [10]:
x[2]

2

In [11]:
x[-1]

26

In [12]:
x[-3:]

array([24, 25, 26])

In [14]:
y = x[4:10:2]
y

array([4, 6, 8])

In [43]:
x[4] = 4
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [18]:
y

array([9999,    6,    8])

In [20]:
xx = x.reshape((3,9))
xx

array([[   0,    1,    2,    3, 9999,    5,    6,    7,    8],
       [   9,   10,   11,   12,   13,   14,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23,   24,   25,   26]])

In [23]:
xx[1]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [24]:
xx[1][6]

15

In [25]:
xx[1,6]

15

In [27]:
xxx = x.reshape((3,3,3))
xxx

array([[[   0,    1,    2],
        [   3, 9999,    5],
        [   6,    7,    8]],

       [[   9,   10,   11],
        [  12,   13,   14],
        [  15,   16,   17]],

       [[  18,   19,   20],
        [  21,   22,   23],
        [  24,   25,   26]]])

In [28]:
xxx[0,1,1]

9999

In [49]:
xx

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [48]:
xx[1,-1] = 17

In [57]:
xx[1:3,-3:]

array([[15, 16, 17],
       [24, 25, 26]])

In [84]:
xx[:,(1,5,2)]

array([[ 1,  5,  2],
       [10, 14, 11],
       [19, 23, 20]])

array([[ 135.74399244,  137.75384003,  238.23378937, ...,  -14.55006131,
         295.92696588,  143.32785349],
       [ 254.21746772,  183.3122234 ,  227.7339786 , ...,   64.16601905,
         300.83036339,  137.51769739],
       [ 184.86162571,   90.41228538,   72.76410782, ...,  171.31570681,
          63.63782809,  247.62787972],
       ...,
       [  38.35565258,   61.01435821,  -78.92020829, ...,  150.00827718,
          -2.24729749,   27.35070885],
       [  42.92493868,   44.13612214,   92.21388318, ...,   53.06291507,
         226.25816636,   18.86318071],
       [ -12.54319405,   29.82333112,    3.78940985, ...,  207.42553804,
          15.48653369, -108.48938624]])

In [6]:
c=(1,1)

In [7]:
img[c[0],c[1]]

183.31222339608448

In [10]:
area = img[c[0]-1:c[0]+2,c[1]-1:c[1]+2]
area

array([[135.74399244, 137.75384003, 238.23378937],
       [254.21746772, 183.3122234 , 227.7339786 ],
       [184.86162571,  90.41228538,  72.76410782]])

In [11]:
blur=np.array([[0.25,0.5,0.25],[0.5,1.0,0.5],[0.25,0.5,0.25]])
blur

array([[0.25, 0.5 , 0.25],
       [0.5 , 1.  , 0.5 ],
       [0.25, 0.5 , 0.25]])

In [12]:
area * blur

array([[ 33.93599811,  68.87692002,  59.55844734],
       [127.10873386, 183.3122234 , 113.8669893 ],
       [ 46.21540643,  45.20614269,  18.19102695]])

In [13]:
np.sum(area * blur) / np.sum(blur)

174.06797202437514

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        , 174.06797202, 142.72630926, ..., 110.72641783,
        179.59624082,   0.        ],
       [  0.        , 133.25992389,  86.80631327, ..., 131.0455339 ,
        158.82448601,   0.        ],
       ...,
       [  0.        ,  53.98108812,  26.96396391, ...,  61.90074986,
         57.08178692,   0.        ],
       [  0.        ,  36.19869819,  50.60742898, ..., 109.1937755 ,
         84.4786542 ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])

In [98]:
mask = img > 100
mask

array([[False,  True, False, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True, False],
       [False, False, False, ..., False, False,  True],
       ...,
       [False,  True,  True, ..., False, False, False],
       [ True, False,  True, ...,  True, False, False],
       [ True, False,  True, ..., False,  True,  True]])

In [95]:
img_copy = img.copy()
img_copy[mask] = 0

In [96]:
img

array([[  40.40524559,  153.1266393 ,   42.18917891, ...,  174.93845352,
         136.15064142,  286.85563228],
       [ 144.97477141,  130.77234672,  107.01380157, ...,  172.7623701 ,
         158.59431348,   32.9891366 ],
       [  85.27289798, -137.40959178,   78.61703509, ...,   -5.18168937,
          85.33961352,  131.47259292],
       ...,
       [  72.75113295,  339.43404216,  105.29320961, ...,  -21.77476391,
         -48.68437922,  -52.18608546],
       [ 219.56896281,   70.89833401,  140.7786858 , ...,  186.49939416,
          69.00132682,   10.34344893],
       [ 122.47863762,  -61.99994408,  126.99399848, ...,  -47.28524142,
         289.86765109,  212.42194169]])

In [97]:
img_copy

array([[  40.40524559,    0.        ,   42.18917891, ...,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        ,   32.9891366 ],
       [  85.27289798, -137.40959178,   78.61703509, ...,   -5.18168937,
          85.33961352,    0.        ],
       ...,
       [  72.75113295,    0.        ,    0.        , ...,  -21.77476391,
         -48.68437922,  -52.18608546],
       [   0.        ,   70.89833401,    0.        , ...,    0.        ,
          69.00132682,   10.34344893],
       [   0.        ,  -61.99994408,    0.        , ...,  -47.28524142,
           0.        ,    0.        ]])

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        , 174.06797202, 142.72630926, ..., 110.72641783,
        179.59624082,   0.        ],
       [  0.        , 133.25992389,  86.80631327, ..., 131.0455339 ,
        158.82448601,   0.        ],
       ...,
       [  0.        ,  53.98108812,  26.96396391, ...,  61.90074986,
         57.08178692,   0.        ],
       [  0.        ,  36.19869819,  50.60742898, ..., 109.1937755 ,
         84.4786542 ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])

47.2 ms ± 845 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [58]:
%timeit blur_image_shift(img, blur)

170 µs ± 1.28 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
