In [9]:
import numpy as np

sample = np.random.normal(loc=[2.,20.], scale=[1.,3.5], size=(3,2))
sample

array([[ 3.76854484, 24.53060727],
       [ 2.93246093, 23.78488256],
       [ 3.5014365 , 14.56889592]])

In [10]:
mu = sample.mean(axis=0)
mu

array([ 3.40081409, 20.96146192])

In [11]:
print('sample:', sample.shape, '| means:', mu.shape)

sample: (3, 2) | means: (2,)


In [12]:
sample - mu

array([[ 0.36773075,  3.56914535],
       [-0.46835316,  2.82342064],
       [ 0.10062241, -6.392566  ]])

## z-score

In [14]:
(sample - sample.mean(axis=0)) / sample.std(axis=0)

array([[ 1.05467692,  0.78780953],
       [-1.34326888,  0.62320737],
       [ 0.28859196, -1.41101691]])